-- ============================================================================
-- Catálogo de motos: familias de motor, modelos comerciales y compatibilidad
--
-- Esquema tomado 1:1 (mismos ids) de un pg_dump de producción, con dos
-- diferencias respecto al dump original:
--   1. `codprod` en las tablas de compatibilidad NO tiene FK a
--      public.repuestos — esa tabla vive en el ERP legado (junto con
--      saprod), no en este proyecto. Acá codprod queda como texto suelto;
--      el cruce real con public.products se hace en la capa de aplicación.
--   2. Las políticas RLS usan public.is_agent() (patrón de este proyecto)
--      en vez del rol `n8n_catalogo_ro` del dump, que no existe acá.
--   3. Los ids son "generated by default as identity" (no "always"): el
--      seed en supabase/seeds/moto_catalog_seed.sql inserta los mismos ids
--      que producción explícitamente, y al final ajusta cada secuencia.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- FAMILIAS_MOTOR / MODELOS_COMERCIALES / MODELO_MOTOR_NEXO
-- Un mismo motor (familia_motor) se reutiliza en muchos modelos comerciales;
-- modelo_motor_nexo es el vínculo muchos-a-muchos que resuelve "qué otros
-- modelos llevan el mismo motor que el mío".
-- ---------------------------------------------------------------------------
create table public.familias_motor (
  id bigint generated by default as identity primary key,
  codigo_motor text not null unique,
  descripcion text,
  created_at timestamptz not null default now()
);

comment on table public.familias_motor is 'Familias de motor por código técnico — el mismo motor se reutiliza en muchos modelos comerciales distintos, y varios fabricantes lo usan.';

create table public.modelos_comerciales (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  anio_desde smallint,
  anio_hasta smallint,
  created_at timestamptz not null default now(),
  constraint modelos_comerciales_anio_valido check (anio_hasta is null or anio_hasta >= anio_desde),
  constraint modelos_comerciales_marca_modelo_anio_desde_key unique (marca, modelo, anio_desde)
);

comment on table public.modelos_comerciales is 'Modelos comerciales tal como los reconoce el cliente (marca + modelo + rango de años), independiente del motor que lleven.';

create index idx_modelos_comerciales_marca_modelo on public.modelos_comerciales (marca, modelo);

create table public.modelo_motor_nexo (
  modelo_comercial_id bigint not null references public.modelos_comerciales (id) on delete cascade,
  familia_motor_id bigint not null references public.familias_motor (id) on delete cascade,
  primary key (modelo_comercial_id, familia_motor_id)
);

comment on table public.modelo_motor_nexo is 'Vínculo muchos-a-muchos entre modelo comercial y familia de motor. Este es el corazón de la compatibilidad cruzada: buscar por acá resuelve "qué otros modelos llevan el mismo motor que el mío".';

-- ---------------------------------------------------------------------------
-- REPUESTO_COMPATIBILIDAD_MOTOR / REPUESTO_COMPATIBILIDAD_MODELO
-- Qué repuesto (codprod, código del ERP legado) calza con qué familia de
-- motor o qué modelo comercial. Sin FK a repuestos: ver nota de cabecera.
-- ---------------------------------------------------------------------------
create table public.repuesto_compatibilidad_motor (
  codprod text not null,
  familia_motor_id bigint not null references public.familias_motor (id) on delete cascade,
  primary key (codprod, familia_motor_id)
);

create index idx_repuesto_compat_motor_familia on public.repuesto_compatibilidad_motor (familia_motor_id);

create table public.repuesto_compatibilidad_modelo (
  codprod text not null,
  modelo_comercial_id bigint not null references public.modelos_comerciales (id) on delete cascade,
  primary key (codprod, modelo_comercial_id)
);

create index idx_repuesto_compat_modelo_modelo on public.repuesto_compatibilidad_modelo (modelo_comercial_id);

-- ---------------------------------------------------------------------------
-- SINONIMOS_BUSQUEDA
-- ---------------------------------------------------------------------------
create table public.sinonimos_busqueda (
  id bigint generated by default as identity primary key,
  termino_jerga text not null,
  termino_catalogo text not null,
  created_at timestamptz not null default now(),
  constraint sinonimos_busqueda_termino_jerga_termino_catalogo_key unique (termino_jerga, termino_catalogo)
);

comment on table public.sinonimos_busqueda is 'Jerga/sinónimos venezolanos -> término real usado en el catálogo. Se consulta en cada búsqueda, sin necesidad de redesplegar la función al agregar uno nuevo.';

-- ---------------------------------------------------------------------------
-- RLS + GRANTS
-- ---------------------------------------------------------------------------
alter table public.familias_motor enable row level security;
alter table public.modelos_comerciales enable row level security;
alter table public.modelo_motor_nexo enable row level security;
alter table public.repuesto_compatibilidad_motor enable row level security;
alter table public.repuesto_compatibilidad_modelo enable row level security;
alter table public.sinonimos_busqueda enable row level security;

create policy "familias_motor_all" on public.familias_motor for all
  using (public.is_agent()) with check (public.is_agent());

create policy "modelos_comerciales_all" on public.modelos_comerciales for all
  using (public.is_agent()) with check (public.is_agent());

create policy "modelo_motor_nexo_all" on public.modelo_motor_nexo for all
  using (public.is_agent()) with check (public.is_agent());

create policy "repuesto_compatibilidad_motor_all" on public.repuesto_compatibilidad_motor for all
  using (public.is_agent()) with check (public.is_agent());

create policy "repuesto_compatibilidad_modelo_all" on public.repuesto_compatibilidad_modelo for all
  using (public.is_agent()) with check (public.is_agent());

create policy "sinonimos_busqueda_all" on public.sinonimos_busqueda for all
  using (public.is_agent()) with check (public.is_agent());

grant select, insert, update, delete on
  public.familias_motor,
  public.modelos_comerciales,
  public.modelo_motor_nexo,
  public.repuesto_compatibilidad_motor,
  public.repuesto_compatibilidad_modelo,
  public.sinonimos_busqueda
to authenticated, service_role;
